### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by Calm99999** [juliango202/jijimaku#5]
C:\Users\Дима>C:\Users\Дима\Desktop\jijimaku-1.05\bin\jijimaku.bat
Error: Could not find or load main class jijimaku.AppMain
Caused by: java.lang.ClassNotFoundException: jijimaku.AppMain

**Comment by manva102019** [comment]
Can you give more details about the issue?

**Comment by Calm99999** [comment]
Actually, I found out through ChatGPT that I didn't have Java 8 installed properly on my PC. I tried to do all these path ''configurations'', but I probably didn't do it the way it should've been done. And I can't run the exe-file for installing Java itself. I don't know. It feels like I'm lacking some programming skills to install Java 8. 

And I think I ''checked" through cmd whether I install Java. And everything worked fine. 

I can't install jre-file. That's why I can't make my PATH work (you need to write "repository" for jre and jdk there)
